#!/bin/bash

#################################################################################
# Vault Initialization Script
# Initializes /opt/vault directory structure on Proxmox deployment
# 
# Creates:
#   - /opt/vault/raw   (ingested content: URLs, PDFs, images)
#   - /opt/vault/wiki  (LLM-generated entries)
#   - /opt/vault/index.md (article index)
#   - /opt/vault/log.md (processing log)
#
# Idempotent: safe to run multiple times
#################################################################################

set -e

# Configuration
VAULT_ROOT="/opt/vault"
VAULT_RAW="$VAULT_ROOT/raw"
VAULT_WIKI="$VAULT_ROOT/wiki"
DIR_PERMISSIONS=755
LOG_FILE="${VAULT_ROOT}/init_vault.log"

# Logging with timestamps
log() {
    local level=$1
    shift
    local message="$@"
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo "[$timestamp] [$level] $message" | tee -a "$LOG_FILE" 2>/dev/null || echo "[$timestamp] [$level] $message"
}

log_info() {
    log "INFO" "$@"
}

log_error() {
    log "ERROR" "$@"
}

#################################################################################
# Main
#################################################################################

log_info "Starting vault initialization"

if [ ! -d "$VAULT_ROOT" ]; then
    log_info "Creating $VAULT_ROOT"
    mkdir -p "$VAULT_ROOT"
    chmod "$DIR_PERMISSIONS" "$VAULT_ROOT"
else
    log_info "$VAULT_ROOT already exists"
fi

if [ ! -d "$VAULT_RAW" ]; then
    log_info "Creating $VAULT_RAW"
    mkdir -p "$VAULT_RAW"
    chmod "$DIR_PERMISSIONS" "$VAULT_RAW"
else
    log_info "$VAULT_RAW already exists"
fi

if [ ! -d "$VAULT_WIKI" ]; then
    log_info "Creating $VAULT_WIKI"
    mkdir -p "$VAULT_WIKI"
    chmod "$DIR_PERMISSIONS" "$VAULT_WIKI"
else
    log_info "$VAULT_WIKI already exists"
fi

if [ ! -d "$VAULT_ROOT/.obsidian" ]; then
    log_info "Creating $VAULT_ROOT/.obsidian"
    mkdir -p "$VAULT_ROOT/.obsidian"
    chmod "$DIR_PERMISSIONS" "$VAULT_ROOT/.obsidian"
else
    log_info "$VAULT_ROOT/.obsidian already exists"
fi

if [ ! -f "$VAULT_ROOT/index.md" ]; then
    log_info "Creating $VAULT_ROOT/index.md"
    cat > "$VAULT_ROOT/index.md" << 'EOF'
# Vault Index

Master index of all articles in the vault.

## Raw Content
Content in `/raw` directory (ingested from URLs, PDFs, images).

## Wiki Entries
Content in `/wiki` directory (LLM-generated entries).

![[log]]

---
Generated by init_vault.sh
EOF
    log_info "index.md created with initial header"
else
    log_info "$VAULT_ROOT/index.md already exists"
fi

if [ ! -f "$VAULT_ROOT/log.md" ]; then
    log_info "Creating $VAULT_ROOT/log.md"
    cat > "$VAULT_ROOT/log.md" << 'EOF'
# Processing Log

Vault processing and synchronization events.

## Timeline
EOF
    log_info "log.md created with initial header"
else
    log_info "$VAULT_ROOT/log.md already exists"
fi

#################################################################################
# Syncthing Configuration
#################################################################################

log_info "Syncthing integration note:"
log_info "Add /opt/vault as a shared folder in Syncthing configuration"
log_info "Manual setup steps:"
log_info "  1. SSH into Proxmox host: ssh user@proxmox-host"
log_info "  2. Edit Syncthing config at ~/.config/syncthing/config.xml"
log_info "  3. Add folder entry for /opt/vault with desired sync peers"
log_info "  4. Restart Syncthing: systemctl restart syncthing (if running as service)"
log_info ""
log_info "Alternative: Configure Syncthing via Web UI at http://localhost:8384"

log_info "Vault initialization complete"
log_info "Vault root: $VAULT_ROOT"
log_info "Permissions: $DIR_PERMISSIONS"
log_info "Log output: $LOG_FILE"

exit 0
