#!/bin/bash
#################################################################################
# init_vault.sh — Initialize Obsidian vault structure for Senji PICS
#
# Creates:
#   - /opt/vault/raw/ (raw captured content)
#   - /opt/vault/wiki/ (processed LLM wiki)
#   - /opt/vault/.obsidian/ (Obsidian config directory)
#   - /opt/vault/index.md (article index with log embed)
#   - /opt/vault/log.md (processing log)
#
# Idempotent: safe to run multiple times
#################################################################################

set -e

# Configuration
VAULT_DIR="${VAULT_DIR:-/opt/vault}"
RAW_DIR="$VAULT_DIR/raw"
WIKI_DIR="$VAULT_DIR/wiki"
OBSIDIAN_DIR="$VAULT_DIR/.obsidian"
INDEX_FILE="$VAULT_DIR/index.md"
LOG_FILE="$VAULT_DIR/log.md"

# Create directory structure
mkdir -p "$RAW_DIR"
mkdir -p "$WIKI_DIR"
mkdir -p "$OBSIDIAN_DIR"

# Create index.md with log embed (Obsidian transclusion syntax)
if [ ! -f "$INDEX_FILE" ]; then
  cat > "$INDEX_FILE" << 'EOF'
# Senji PICS — Article Index

## Overview
This vault contains captured articles, PDFs, images, and video transcripts processed through the Senji Personal Information Capture System.

## Structure
- **raw/** — Original captured content (HTML, PDF text, images)
- **wiki/** — LLM-processed wiki entries with structured frontmatter
- **log.md** — Processing log with timestamps and operation results

## Processing Log
![[log]]

---

Generated by senji-gateway initialization script
EOF
fi

# Create empty log.md if not exists
if [ ! -f "$LOG_FILE" ]; then
  cat > "$LOG_FILE" << 'EOF'
# Processing Log

## Format
Each entry: `[TIMESTAMP] [OPERATION] [SOURCE] [STATUS]`

---
EOF
fi

echo "✅ Vault initialized at $VAULT_DIR"
echo "   - raw/: $RAW_DIR"
echo "   - wiki/: $WIKI_DIR"
echo "   - .obsidian/: $OBSIDIAN_DIR"
echo "   - index.md: $INDEX_FILE"
echo "   - log.md: $LOG_FILE"
